### ISSUE TITLE
Changing Popularity Content Alpha Value

### ISSUE THREAD

**Issue by mmaizan** [mesarpe/socialccnsim#2]
Hi MR Bernardini,

Its me Maizan that have contacted u through email..
I'm currently working on using your SocialCCNSIm but having some problem with changing the alpha value for content popularity ZIpf distribution..
Could u guide me on this..
Thanks

**Comment by mesarpe** [comment]
SocialCCNSim executes traces with instructions for consuming/publishing data.
For generating traces with/ personalized popularity settings. Please take a look at sonetor:
Http://GitHub.com/mesarpe/sonetor
